- src/main/java/com/gradle/CustomBuildScanEnhancements.java
Search links for custom values must be added during a 'buildFinished' event,
in order to ensure that the server URL is set to it's final value.
The previous implementation did this by registering a separate 'buildFinished'
listener for each search link, but the background process that captured git metadata
would occasionally register after the build was complete.
In order to avoid the warnings issued in this case, we now register a single
buildFinished listener, with a thread-safe implementation that will collect all
registered build scans. With this change, if the git metadata process completes after
the build is complete, then the search link is ignored and no warning is issued.
Note that configuration-cache compliance necessitated the use of a static class
to register as a …
> Avoid calling `buildFinished` after build is finished

- build.gradle
`plugin-publish` Gradle plugin starting from version 0.14.0 does not publish the signature files when used with the `maven-publish` Gradle plugin.
Until this bug is fixed, this PR:
- keeps the `maven-publish` plugin so users can still build and publish to their internal repository
- configures the `plugin-publish` so it ignores the `maven-publish` model and publish the signatures
> Fix missing signature files when publishing to the plugin portal

- release/changes.md
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
Replaces `gradle.allprojects` call with `gradle.afterProject` since the former is not compatible with Gradle project isolation.
Fixes #24
> Fix error with Gradle project isolation enabled

- .github/workflows/build-verification.yml
- .github/workflows/wrapper-upgrade-execution.yml
Separating the setup of the Gradle build tool from actual build invocation
is more idiomatic to GH Actions in general, and provides a clearer separation
of responsibilities.
> Add "Set up Gradle" step to GHActions workflows

- src/main/java/com/gradle/CommonCustomUserDataGradlePlugin.java
- src/main/java/com/gradle/ProxyFactory.java
When the GE plugin is applied by the build and the CCUD plugin via an
init script, the Gradle Enterprise extension and types it references
are loaded by a different classloader than the classes in the CCUD
plugin. To work around this issue, the Gradle Enterprise types are now
accessed via dynamic proxies that "translate" between the different
class loaders at runtime.
> Proxy Gradle Enterprise plugin types to work around ClassLoader issues

- src/main/java/com/gradle/CommonCustomUserDataGradlePlugin.java
Related to https://github.com/gradle/ge/issues/16749.
See https://github.com/gradle/ge/pull/16816
This changes adds a publicly available **static** `apply` method on the CCUD gradle plugin in order to make its application work in the Gradle Enterprise build.
> Provide static application method

- settings.gradle
Very nice: https://ge.solutions-team.gradle.com/s/iqb6mqnsm2aw6/performance/build-cache#remote-cache-use-access-key
> Use Gradle Enterprise build cache node connector

- release/changes.md
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
Favor `idea.vendor.name` system property over `android.injected.invoked.from.ide` which is populated during _Intellij_ and _Android studio_ syncs
fixes https://github.com/gradle/common-custom-user-data-gradle-plugin/issues/90
Signed-off-by: Jerome Prinet <jprinet@gradle.com>
> Fix Intellij tag on IDE syncs

- src/main/java/com/gradle/CustomBuildScanEnhancements.java
Builds on Jenkins commonly run multiple invocations of Gradle, generating multiple build scans. A common question when looking at a build scan is "which other builds ran in this job/pipeline?". Our current custom links do not easily link back to this query in GE.
Currently, there are 4 custom links for a Jenkins build. One of these links back to Jenkins (based on `BUILD_URL`). The other three link back to custom value searches as follows:
- All CI builds run on a given node (based on `NODE_NAME`)
- All CI builds with a particular job name (based on `JOB_NAME`)
- All CI builds with a particular stage name (based on `STAGE_NAME`)
We also capture as a custom value the `BUILD_NUMBER` environment variable as `CI build number`. This CI build number correlates to one run of the pipeline, but the …
> Add a link to all build scans with same Jenkins build number and job name

- .github/workflows/build-verification.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/wrapper-upgrade-execution.yml
Deprecation warnings appear when running actions/checkout@v2, this is fixed when upgrading to actions/checkout@v3
> Upgrade actions/checkout to v3

- .github/workflows/build-verification.yml
- .github/workflows/wrapper-upgrade-execution.yml
- Upgrade crazy-max/ghaction-import-gpg to latest
- Upgrade actions/setup-java to v3
> Upgrade some Github actions to get rid of deprecation warnings

- README.md
- release/changes.md
- src/main/java/com/gradle/Overrides.java
- src/main/java/com/gradle/Utils.java
Currently, environment variable/system property overrides only the HTTP build cache settings. This pull request adds conditional logic to also apply the same overrides to a project that utilizes the Gradle Enterprise build cache connector.
> Allow overrides to apply to Gradle Enterprise build cache connector

- src/main/java/com/gradle/CiUtils.java
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
CI related methods are use in several places and copy / pasting ([here](https://github.com/gradle/common-custom-user-data-gradle-plugin/blob/97e48144a0d4370d3e2bb409bcba02878adb4aa7/src/main/java/com/gradle/CustomBuildScanEnhancements.java#L273) and [there](https://github.com/gradle/common-custom-user-data-gradle-plugin/blob/97e48144a0d4370d3e2bb409bcba02878adb4aa7/src/main/java/com/gradle/CustomBuildScanEnhancements.java#L404)) is not ideal
This PR aims to centralize this in a utility class, the methods are exposed as static methods. 
Q: Instance Vs static?
Creating an instance of a utility class doesn't simplify the logic. If we do so, we should apply the same pattern to the existing `Utils` class as well.
> Extract ci logic to a utility class

- release/changes.md
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
- src/main/java/com/gradle/Utils.java
The PR aims to capture CI metadata at execution time (in a `buildFinished` block), therefore preventing configuration cache invalidation if a property changes (ie. `CI build number`)
Teamcity metadata are now fetched from a build file generated by Teamcity, as project properties set via an `init script` can't be easily read at execution time through a [Provider](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ProviderFactory.html#gradleProperty-java.lang.String-) due to https://github.com/gradle/gradle/issues/23572.
Metadata initially read in the `projectEvaluated` callback are now read through a `Provider` in order to fix configuration cache restore scenarii.
Note that Teamcity is not yet compatible with configuration cache due to …
> Capture CI related metadata at execution time

- release/changes.md
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
- src/main/java/com/gradle/Utils.java
The PR aims to capture CI metadata and IDE metadata at execution time (in a `buildFinished` block), therefore preventing configuration cache invalidation if a property changes (ie. `CI build number`) and allow correct execution of configuration cache restore scenarii.
Teamcity metadata are now fetched from a build file generated by Teamcity, as project properties set via an init script can't be easily read at execution time through a [Provider](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ProviderFactory.html#gradleProperty-java.lang.String-) due to https://github.com/gradle/gradle/issues/23572.
Note that Teamcity is not yet compatible with configuration cache due to [this](https://youtrack.jetbrains.com/issue/TW-71916)
fixes …
> Capture IDE related metadata at execution time

- release/changes.md
- src/main/java/com/gradle/CiUtils.java
- src/main/java/com/gradle/CommonCustomUserDataGradlePlugin.java
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
- src/main/java/com/gradle/ProxyFactory.java
- src/main/java/com/gradle/Utils.java
The PR aims to capture CI metadata and IDE metadata at execution time (in a `buildFinished` block), therefore preventing configuration cache invalidation if a property changes (ie. `CI build number`) and allow correct execution of configuration cache restore scenarii.
Teamcity metadata are now fetched from a build file generated by Teamcity, as project properties set via an init script can't be easily read at execution time through a [Provider](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ProviderFactory.html#gradleProperty-java.lang.String-) due to https://github.com/gradle/gradle/issues/23572.
Note that Teamcity is not yet compatible with configuration cache due to [this](https://youtrack.jetbrains.com/issue/TW-71916)
fixes …
> Capture CI and IDE related metadata at execution time

- README.md
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
- src/main/java/com/gradle/Overrides.java
- src/main/java/com/gradle/Utils.java
- Using the GE build cache connector, the remote build cache URL provided via `gradle.cache.remote.url` is split up and the _server_ and _path_ parts set individually on the GE connector API
- The behavior of configuring the BT and the GE connector is now more similar in terms replacing/appending a path provided via `gradle.cache.remote.path`
> User can configure BT and GE build cache connector with the same sys prop `gradle.cache.remote.url`

- src/main/java/com/gradle/CustomGradleEnterpriseConfig.java
The commented sample code in CustomGradleEnterpriseConfig contains two lines that are outdated. This change:
- Uses the new capture API recommended as of Gradle Enterprise Gradle Plugin 3.7
- Configures the GradleEnterpriseBuildCache connector
> Updates to CustomGradleEnterpriseConfig commented sample code

- build.gradle
Resolves #134
Allows users to view release notes from the plugin portal and gives them an idea of what will be gained by updating to that version.
The contents of the release notes file are read in a way that supports configuration caching using `Providers.fileContents()`. This functionality was extracted into its own method, and setting `githubRelease.body` has been updated to use this. 
Configuration cache compatibility was verified using the following steps...
1. Run `./gradlew clean`
2. Run `./gradlew generatePomFileForCommonCustomUserDataPluginMarkerMavenPublication` to generate the `build/publications/commonCustomUserDataPluginMarkerMaven/pom-default.xml` file containing the release notes in `release/changes.md`. The logs indicate a new configuration cache entry has been stored.
3. …
> Add release notes to plugin description

- release/changes.md
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
Fixes #109
When creating links to GitHub Actions builds, the plugin now references the environment variable `GITHUB_SERVER_URL` instead of hardcoding `https://github.com/`.
When creating build scan links to the remote repository, the plugin now uses a regex to parse out the correct url instead of hardcoding `https://github.com/` or `https://gitlab.com`.
Published the CCUD plugin to Maven local for testing.
HTTP URL variations tested:
* `https://github.com/gradle/common-custom-user-data-gradle-plugin.git`: https://ge.solutions-team.gradle.com/s/r4phrtqudyt2y
* `https://github.com:443/gradle/common-custom-user-data-gradle-plugin.git`: https://ge.solutions-team.gradle.com/s/lbibg7tgoq6ea
* `https://github.somecompany.com/gradle/common-custom-user-data-gradle-plugin.git`: …
> Support build scan links to alternate GitHub URLs

- src/main/java/com/gradle/CustomBuildScanEnhancements.java
Fixes "GitHub Actions build" (and others) custom link creation failure caused by neglecting to call `.get()` on optional `gitHubUrl`.
GitHub Actions [build scan](https://ge.solutions-team.gradle.com/s/kfjkhd2o4kspi) verifying that all custom links are correctly created.
GitHub Actions [build scan](https://ge.solutions-team.gradle.com/s/3e3cjt4ncw2oo) before this fix was applied. Notice the missing custom links.
> Call .get() on optional gitHubUrl

- build.gradle
Addresses [this suggestion](https://github.com/gradle/common-custom-user-data-gradle-plugin/pull/156#discussion_r1159254525)
Assign releaseNotes() to variable for re-use instead of re-reading the release notes
Verified `./gradlew generatePomFileForCommonCustomUserDataPluginMarkerMavenPublication` produces the correct description in `build/publications/commonCustomUserDataPluginMarkerMaven/pom-default.xml`:
```
<description>[FIX] Generates incorrect "GitHub Actions Build" and "GitHub/GitLab Source" links to repositories not hosted at github.com or gitlab.com</description>
```
> Read release notes only once

- build.gradle
Setting version to `Property<String>` causes incorrect jar file names and incorrect version in pom files, as other tasks do not account for `version` (which is of type `Object`) being a `Property`.
Though this results in the version file being read eagerly, we still have achieved the main goal of configuration cache compatibility when reading the version file.
* `./gradlew clean generatePomFileForCommonCustomUserDataPluginMarkerMavenPublication` generates correct version in `pom-default.xml`: `<version>1.10.11</version>`
* `./gradlew clean generatePomFileForCommonCustomUserDataPluginMarkerMavenPublication` stores new configuration cache entry when `version.txt` is updated, and the configuration cache entry is reused when it has not been updated. The version in `pom-default.xml` is updated …
> Set version to String

- .github/workflows/build-verification.yml
- .github/workflows/wrapper-upgrade-execution.yml
Auto-provisioning can come with a tradeoff of slower builds when a toolchain is auto-provisioned. For our CI builds, we should disable auto-provisioning to make sure we are not taking a performance hit by provisioning toolchains on every build.
> Disable toolchain provisioning in CI

- .github/workflows/combine-dependabot-prs.yml
GITHUB_TOKEN credential is not allowed to trigger other workflows, so checks were not running for combine-prs PRs. Using bot-githubactions credentials to create the combine-prs PR resolves this.
> Use bot-githubactions to execute combine-prs action

- .github/workflows/submit-github-dependency-graph.yml
This workflow will calculate and submit a GitHub Dependency Graph for any change to the 'main' branch. This allows GitHub to display the dependencies in the "Insights" tab, and to inspect all dependencies for security vulnerabilities.
> Add workflow to submit GH dependency graph

- release/changes.md
- src/main/java/com/gradle/Utils.java
- src/test/java/com/gradle/UtilsTest.java
Fixes #191
Update `GIT_REPO_URI_PATTERN` to properly handle embedded user info in git repository URL
* `https://gitlab-svc-user:secret@gitlab.self-hosted.com/foo/bar.git`: https://ge.solutions-team.gradle.com/s/b54q5wdxtkef4#info
* `https://github.com/gradle/common-custom-user-data-gradle-plugin.git`: https://ge.solutions-team.gradle.com/s/yv6hrmnldvo3e#info
> Handle embedded user info in git repo url

- release/changes.md
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
Adding a maxParallelForks custom value for each test task caused sometimes unnecessary noise in build scans. An example of how to add this custom value has instead been added to the build config samples repository ([link](https://github.com/gradle/gradle-enterprise-build-config-samples/tree/main/build-data-capturing-gradle-samples/capture-max-parallel-forks)).
[Build scan](https://ge.solutions-team.gradle.com/s/dy4iiufwyn24c/custom-values) showing custom values with [CCUD plugin including these changes applied](https://ge.solutions-team.gradle.com/s/dy4iiufwyn24c/build-dependencies?focusedDependency=WzAsMSwxLFswLDEsWzFdXV0&focusedDependencyView=details&toggled=W1swXSxbMCwxXV0) no longer include `maxParallelForks`
Verified functional tests pass when setting …
> Remove maxParallelForks custom value

- .github/workflows/build-verification.yml
- .github/workflows/submit-github-dependency-graph.yml
- .github/workflows/wrapper-upgrade-execution.yml
- Replaces use of `gradle/gradle-build-action` with `gradle/actions/setup-gradle`.
- Replaces custom dependency graph workflow with simpler one using `gradle/actions/dependency-submission`.
> Use gradle/actions/setup-gradle and gradle/actions/dependency-submission

- src/main/java/com/gradle/CustomBuildScanEnhancements.java
- src/main/java/com/gradle/Utils.java
The `orElse` API is available only starting with Gradle 5.6: https://e.grdev.net/s/zna6geusbluio/tests/task/:common-custom-user-data-gradle-plugin-test-func:test_Gradle_4_10_3_GradleJDK_11_daily/details/com.gradle.custom.CommonCustomUserDataGradlePluginFuncTest/Checking%20IDE%20tags%20and%20custom%20values%20for%20New%20IJ%20version%20%5BbuildToolVersion%3D4.10.3%2C%20gradleJavaVersion%3D11%5D?focused-exception-line=0-11&top-execution=1
Caused by https://github.com/gradle/common-custom-user-data-gradle-plugin/commit/90c8241ebd387910a043d4edda488f479e6f58fc
> Fix the usage of `orElse` provider API

- release/changes.md
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
Revert detached head detection as it introduces breaking changes. Will get reapplied after a minor release.
This PR reverts the following PRs:
PR #240 - Improve tags/values in GitHub Actions pull_request workflows using git detached HEAD state
PR #270  - Improve tags/values in Jenkins where GIT_BRANCH is available
> Revert detached head detection

- release/changes.md
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
This reverts commit 27fd312e681f06606a2c1512916dfb3cdc4a147a (PR #276 merge)
Effectively, this re-applies work done in PRs:
PR https://github.com/gradle/common-custom-user-data-gradle-plugin/pull/240 - Improve tags/values in GitHub Actions pull_request workflows using git detached HEAD state
PR https://github.com/gradle/common-custom-user-data-gradle-plugin/pull/270 - Improve tags/values in Jenkins where GIT_BRANCH is available
> Reapply detached head work

- build.gradle
- src/compatibilityApi/java/com/gradle/ccud/adapters/BuildScanAdapter.java
- src/develocityCompatibility/java/com/gradle/ccud/adapters/develocity/BuildScanConfigurationAdapter.java
- src/develocityCompatibilityTest/java/com/gradle/ccud/adapters/develocity/BuildScanConfigurationAdapterTest.java
- src/develocityCompatibilityTest/java/com/gradle/ccud/adapters/develocity/DevelocityConfigurationAdapterTest.java
- src/enterpriseCompatibility/java/com/gradle/ccud/adapters/enterprise/BuildScanExtensionAdapter.java
- src/enterpriseCompatibility/java/com/gradle/ccud/adapters/enterprise/BuildScanExtension_1_X_Adapter.java
- src/enterpriseCompatibilityTest/java/com/gradle/ccud/adapters/enterprise/BuildScanExtensionAdapterTest.java
- src/enterpriseCompatibilityTest/java/com/gradle/ccud/adapters/enterprise/BuildScanExtension_1_X_AdapterTest.java
- src/enterpriseCompatibilityTest/java/com/gradle/ccud/adapters/enterprise/GradleEnterpriseExtensionAdapterTest.java
In RC2, the termsOfService APIs have been renamed to termsOfUse. This commit uses the new terminology in the adapter APIs + fixes compilation errors caused by the breaking changes in the RC
> Use "Terms of Use" terminology instead of "Terms of Service"

- build.gradle
Following up on https://github.com/gradle/common-custom-user-data-gradle-plugin/pull/286#discussion_r1531851374.
I did not get any suggestions from the BT team, so I went with the other alternative @runningcode suggested.
> Disable the default JAR task in favor of the shadow JAR task

- build.gradle
This ensures no tasks are created eagerly in `build.gradle`. 
[Configuration build scan before](https://ge.solutions-team.gradle.com/s/rlwc3vn5y726w/performance/configuration?details=code-unit-build.gradle!:&openScriptsAndPlugins=WyJjb2RlLXVuaXQtYnVpbGQuZ3JhZGxlIl0)
[Configuration after build scan here](https://ge.solutions-team.gradle.com/s/u3yd5goebzl4q/performance/configuration?details=code-unit-build.gradle!:&openScriptsAndPlugins=WyJjb2RlLXVuaXQtY29tLmdyYWRsZS5wbHVnaW4tcHVibGlzaCIsImNvZGUtdW5pdC1idWlsZC5ncmFkbGUiXQ).
> Ensure task configuration is lazy

- src/main/java/com/gradle/CustomBuildScanEnhancements.java
Fixes issue https://github.com/gradle/common-custom-user-data-gradle-plugin/issues/295.
Scans after the fix:
- with `export GITHUB_HEAD_REF=someBranch`: [scan](https://ge.solutions-team.gradle.com/s/aao45aos6qys6/custom-values#L6)
- with `export GITHUB_HEAD_REF= `: [scan](https://ge.solutions-team.gradle.com/s/q72quu37enkoq/custom-values)
> Fixed empty PR branch custom value

- build.gradle.kts
- release/distribution/NOTICE
This PR adds a NOTICE file to the root of the project. The NOTICE file includes the licenses of all runtime dependencies, as can be seen in [this build scan](https://ge.solutions-team.gradle.com/s/rh6xon4ychuli/dependencies?toggled=W1swXSxbMCwyXV0).
Both the NOTICE and LICENSE files are then included in all assembled JAR files.
> NOTICE file is added and included in all assembled JAR files along with LICENSE

- src/main/java/com/gradle/CommonCustomUserDataGradlePlugin.java
- src/main/java/com/gradle/CustomBuildScanEnhancements.java
- src/main/java/com/gradle/Utils.java
Fixed getting git data when the gradle build is started from a different directory and given a path to the repository. This can happen if the build is started with the `-p` / `--project-dir` argument, or when using the [GradleConnector](https://docs.gradle.org/current/javadoc/org/gradle/tooling/GradleConnector.html) as the main entrypoint - which is what is used by the VSCode [gradle build server](https://devblogs.microsoft.com/java/new-build-server-for-gradle/), added by [gradle-java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) VSCode extension.
To overcome this issue, I've added the `-C <root-project-path>` argument when running git commands, which will take care of such cases.
I will investigate and open similar PRs for other CCUD implementations if we …
> Fixed getting git metadata when started from a different dir to the project

- src/main/java/com/gradle/CustomBuildScanEnhancements.java
Added setting CI Action and CI job id custom values on github action builds. [This](https://github.com/ribafish/reproducers/actions/runs/16146564695) is an example GHA builds (the `build` scan), with the [scan](https://ge.solutions-team.gradle.com/s/ykzv2537i72te) having two custom values (and search links) added: [CI job id](https://ge.solutions-team.gradle.com/s/ykzv2537i72te/custom-values#L0) and [CI step id](https://ge.solutions-team.gradle.com/s/ykzv2537i72te/custom-values#L3). This will be helpful when you've got multiple builds running consecutively and are passing in arguments that affect those builds, but are not captured in a build scan (best example are Maven profiles for CCUD Maven).
When this is accepted I will do the same for CCUD Maven (and sbt). 
Closes …
> Added setting CI Action and CI job id custom values on github action builds

- .github/workflows/build-verification.yml
With these changes we're now running our integration test verifying the build using CCUD completes with a locally published current version of CCUD. 
I've added testing from Gradle 5.0 onwards on every major version + Gradle 6.5, where the [forUseAtConfigurationTime](https://docs.gradle.org/6.5/javadoc/org/gradle/api/provider/Provider.html#forUseAtConfigurationTime--) was added. It's also configured to run on the current and release candidate gradle versions.
> Verify build improvements

- src/main/java/com/gradle/CustomBuildScanEnhancements.java
This PR adds capturing of run number & attempt for GitHub Actions builds. The following values have been added:
- `CI run attempt` – The value of [`GITHUB_RUN_ATTEMPT`](https://docs.github.com/en/actions/reference/workflows-and-actions/variables#:~:text=example%2C%2090.-,GITHUB_RUN_ATTEMPT,-A%20unique%20number)  if present
- `CI run number` – The value of [`GITHUB_RUN_NUMBER`](https://docs.github.com/en/actions/reference/workflows-and-actions/variables#:~:text=example%2C%201658821493.-,GITHUB_RUN_NUMBER,-A%20unique%20number) if present
In addition, the following links have been updated:
- `GitHub Actions build` – If `GITHUB_RUN_ATTEMPT` is present, the attempt will be included in the path of the URL
- `CI run build scans` –  If `GITHUB_RUN_ATTEMPT` is present, the attempt will be included …
> Capture run number & attempt for GitHub Actions builds
